# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=50)),
                ('mgrID', models.CharField(max_length=10)),
                ('mgrName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('managerID', models.CharField(max_length=10)),
                ('managerName', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('zone', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
