# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPLEMENTATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
