# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPLEMENTATION', '0002_auto_20180320_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('match', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('choice', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
